### ISSUE TITLE
Is 1.21 planned

### ISSUE THREAD

**Issue by HatTrkPatrk** [Estecka/mc-invariable-paintings#14]
Hi, I'm making preparations to setup a 1.21 SMP Fabric server for someone and I'm going through their requested modlist to see if support is planned.

Not asking per se for a release date/timetable but I do want to ask if a 1.21 version of this mod is at least planned. Thank you! (And sorry for being That Guy™ asking about versions lol)

**Comment by Estecka** [comment]
I plan to, but I won't start working on it until that version is realeased and set in stone. I expect there might be some difficulties porting it due to the new data-driven paintings; at the very least I know CITs won't work properly without some major refactoring.

**Comment by Estecka** [comment]
Up on modrinth as v2.1.0+1.21
